# Generated by Django 4.0.4 on 2022-05-29 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course',
        ),
        migrations.AddField(
            model_name='courses',
            name='number_of_students',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.students'),
        ),
        migrations.AddField(
            model_name='courses',
            name='time_of_begining',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='time_of_end',
            field=models.TimeField(null=True),
        ),
    ]
