# Generated by Django 4.0.4 on 2022-05-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_students_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='students',
        ),
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(to='app.students'),
        ),
    ]
