# Generated by Django 4.0.4 on 2022-05-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_attendance_comment_attendance_course_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type_of_file', models.CharField(blank=True, choices=[('homework', 'Homework'), ('ClassVideo', 'classvideo')], max_length=50)),
                ('fileUrl', models.FileField(blank=True, db_column='file_url', upload_to='files/')),
            ],
        ),
    ]
