# Generated by Django 4.0.4 on 2022-05-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_files_date_files_instructor_files_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
