# Generated by Django 4.0.4 on 2022-06-04 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_files_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='link',
            new_name='link_for_homework',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='fileUrl',
            new_name='video_of_class',
        ),
        migrations.AddField(
            model_name='files',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.courses'),
        ),
    ]
