# Generated by Django 4.0.4 on 2022-06-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_link_files_link_for_homework_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='student',
        ),
    ]
