# Generated by Django 4.0.4 on 2022-06-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_files_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructors',
            name='instructor_of_courses',
        ),
        migrations.AddField(
            model_name='instructors',
            name='instructor_of_courses',
            field=models.ManyToManyField(through='app.Courses', to='app.instructors'),
        ),
    ]
