# Generated by Django 4.0.4 on 2022-06-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_instructors_instructor_of_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructors',
            name='instructor_of_courses',
        ),
        migrations.AddField(
            model_name='instructors',
            name='instructor_of_courses',
            field=models.TextField(blank=True),
        ),
    ]
