# Generated by Django 4.0.4 on 2022-06-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_assistant_rename_courses_course_rename_files_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistant_of_courses',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instructor_of_courses',
            field=models.TextField(),
        ),
    ]
